//! convert.py differential tests (vectors generated by tools/gen_convert_vectors.py, 1.2.0).
//!
//! The shapes in the vectors are shape dictionaries after Python's `clean_shape`; the test has a
//! small parser for them (including `src` / `from` / `gaps`) instead of reimplementing clean_shape.

mod common;

use common::*;
use serde_json::Value;
use spiderweb_core::Pt;
use spiderweb_core::convert as Cv;
use spiderweb_core::shape::{
    Align, Ends, Fill, Kind, Shape, ShapeFrom, Stroke, Sym, Tumour, TumourShape, TumourSide,
    TumourWrap,
};

fn close(a: f64, b: f64) -> bool {
    let d = (a - b).abs();
    d <= 1e-9 || d <= 1e-9 * a.abs().max(b.abs())
}

fn close_f(got: f64, want: f64, ctx: &str) {
    assert!(close(got, want), "{ctx}: got={got} want={want}");
}

fn assert_pts_close(got: &[Pt], want: &[Pt], ctx: &str) {
    assert_eq!(
        got.len(),
        want.len(),
        "{ctx}: different number of points got={got:?} want={want:?}"
    );
    for (k, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        assert!(
            close(g[0], w[0]) && close(g[1], w[1]),
            "{ctx}[{k}]: got={g:?} want={w:?}"
        );
    }
}

fn assert_strokes_close(got: &[Stroke], want: &[Stroke], ctx: &str) {
    assert_eq!(got.len(), want.len(), "{ctx}: different number of strokes");
    for (k, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        assert_stroke_close(g, w, &format!("{ctx}[{k}]"));
    }
}

fn assert_stroke_close(got: &Stroke, want: &Stroke, ctx: &str) {
    assert_eq!(got.src(), want.src(), "{ctx}.src");
    match (got, want) {
        (
            Stroke::Poly {
                pts: gp,
                free: gf,
                smooth: gs,
                k: gk,
                ..
            },
            Stroke::Poly {
                pts: wp,
                free: wf,
                smooth: ws,
                k: wk,
                ..
            },
        ) => {
            assert_pts_close(gp, wp, &format!("{ctx}.pts"));
            assert_eq!(gf, wf, "{ctx}.free");
            assert_eq!(gs, ws, "{ctx}.smooth");
            close_f(*gk, *wk, &format!("{ctx}.k"));
        }
        (
            Stroke::Curve {
                pts: gp,
                sharp: gsh,
                sym: gsy,
                ..
            },
            Stroke::Curve {
                pts: wp,
                sharp: wsh,
                sym: wsy,
                ..
            },
        ) => {
            assert_pts_close(gp, wp, &format!("{ctx}.pts"));
            assert_eq!(gsh, wsh, "{ctx}.sharp");
            assert_eq!(gsy, wsy, "{ctx}.sym");
        }
        (Stroke::Arc { pts: gp, k: gk, .. }, Stroke::Arc { pts: wp, k: wk, .. }) => {
            assert_pts_close(gp, wp, &format!("{ctx}.pts"));
            close_f(*gk, *wk, &format!("{ctx}.k"));
        }
        (Stroke::Ellipse { box_: gb, .. }, Stroke::Ellipse { box_: wb, .. }) => {
            for j in 0..4 {
                close_f(gb[j], wb[j], &format!("{ctx}.box[{j}]"));
            }
        }
        _ => panic!("{ctx}: different stroke kind got={got:?} want={want:?}"),
    }
}

fn assert_tumour_close(got: &Tumour, want: &Tumour, ctx: &str) {
    assert_eq!(got.on, want.on, "{ctx}.on");
    assert_eq!(got.shape, want.shape, "{ctx}.shape");
    close_f(got.size, want.size, &format!("{ctx}.size"));
    close_f(got.length, want.length, &format!("{ctx}.length"));
    close_f(got.dist, want.dist, &format!("{ctx}.dist"));
    assert_eq!(got.side, want.side, "{ctx}.side");
    assert_eq!(got.wrap, want.wrap, "{ctx}.wrap");
    close_f(got.start, want.start, &format!("{ctx}.start"));
    close_f(got.end, want.end, &format!("{ctx}.end"));
    close_f(got.ease, want.ease, &format!("{ctx}.ease"));
    assert_eq!(got.fit, want.fit, "{ctx}.fit");
    assert_eq!(got.seed, want.seed, "{ctx}.seed");
    assert_eq!(got.mirror, want.mirror, "{ctx}.mirror");
    close_f(got.k, want.k, &format!("{ctx}.k"));
}

fn assert_shape_close(got: &Shape, want: &Shape, ctx: &str) {
    assert_eq!(got.kind, want.kind, "{ctx}.kind");
    assert_pts_close(&got.pts, &want.pts, &format!("{ctx}.pts"));
    close_f(got.vel0, want.vel0, &format!("{ctx}.vel0"));
    close_f(got.vel1, want.vel1, &format!("{ctx}.vel1"));
    assert_eq!(got.end_dot, want.end_dot, "{ctx}.end_dot");
    assert_eq!(
        got.vel_env.len(),
        want.vel_env.len(),
        "{ctx}.vel_env length differs"
    );
    for (k, (g, w)) in got.vel_env.iter().zip(want.vel_env.iter()).enumerate() {
        assert!(
            close(g[0], w[0]) && close(g[1], w[1]),
            "{ctx}.vel_env[{k}]: got={g:?} want={w:?}"
        );
    }
    match (&got.tumour, &want.tumour) {
        (None, None) => {}
        (Some(g), Some(w)) => assert_tumour_close(g, w, &format!("{ctx}.tumour")),
        pair => panic!("{ctx}.tumour: got={pair:?}"),
    }
    assert_eq!(got.smooth, want.smooth, "{ctx}.smooth");
    close_f(got.k, want.k, &format!("{ctx}.k"));
    assert_eq!(got.sharp, want.sharp, "{ctx}.sharp");
    assert_eq!(got.sym, want.sym, "{ctx}.sym");
    assert_eq!(got.gaps, want.gaps, "{ctx}.gaps");
    assert_eq!(got.name, want.name, "{ctx}.name");
    assert_strokes_close(&got.strokes, &want.strokes, &format!("{ctx}.strokes"));
    assert_eq!(got.fill, want.fill, "{ctx}.fill");
    close_f(got.gate, want.gate, &format!("{ctx}.gate"));
    assert_eq!(got.align, want.align, "{ctx}.align");
    assert_eq!(got.ends, want.ends, "{ctx}.ends");
    assert_eq!(got.union, want.union, "{ctx}.union");
    assert_eq!(got.apart, want.apart, "{ctx}.apart");
    assert_eq!(got.notes, want.notes, "{ctx}.notes");
    assert_eq!(got.own_vel, want.own_vel, "{ctx}.own_vel");
    match (&got.from, &want.from) {
        (None, None) => {}
        (Some(g), Some(w)) => {
            assert_shape_from_close(g, w, &format!("{ctx}.from"));
        }
        pair => panic!("{ctx}.from: got={pair:?}"),
    }
}

fn assert_shape_from_close(got: &ShapeFrom, want: &ShapeFrom, ctx: &str) {
    assert_eq!(
        got.shapes.len(),
        want.shapes.len(),
        "{ctx}.shapes count differs"
    );
    for (k, (g, w)) in got.shapes.iter().zip(want.shapes.iter()).enumerate() {
        assert_shape_close(g, w, &format!("{ctx}.shapes[{k}]"));
    }
    assert_strokes_close(&got.strokes, &want.strokes, &format!("{ctx}.strokes"));
    assert_pts_close(&got.pts, &want.pts, &format!("{ctx}.pts"));
}

// ---------------------------------------------------------------- shape dictionary -> Shape

fn kind_of(s: &str) -> Kind {
    match s {
        "line" => Kind::Line,
        "poly" => Kind::Poly,
        "free" => Kind::Free,
        "curve" => Kind::Curve,
        "arc" => Kind::Arc,
        "custom" => Kind::Custom,
        "funnel" => Kind::Funnel,
        other => panic!("unknown kind {other}"),
    }
}

fn fill_of(s: &str) -> Fill {
    match s {
        "empty" => Fill::Empty,
        "fill" => Fill::Fill,
        "spam" => Fill::Spam,
        "outline_spam" => Fill::OutlineSpam,
        other => panic!("unknown fill {other}"),
    }
}

fn align_of(s: &str) -> Align {
    match s {
        "auto" => Align::Auto,
        "aligned" => Align::Aligned,
        "centred" => Align::Centred,
        other => panic!("unknown align {other}"),
    }
}

fn ends_of(s: &str) -> Ends {
    match s {
        "round" => Ends::Round,
        "keep" => Ends::Keep,
        "drop" => Ends::Drop,
        "min" => Ends::Min,
        "stretch" => Ends::Stretch,
        other => panic!("unknown ends {other}"),
    }
}

fn sym_of(v: &Value) -> Option<Sym> {
    match v.as_str() {
        Some("mirror") => Some(Sym::Mirror),
        Some("turn") => Some(Sym::Turn),
        _ => None,
    }
}

fn stroke_of(v: &Value) -> Stroke {
    let kind = v["kind"]
        .as_str()
        .unwrap_or_else(|| panic!("stroke has no kind: {v}"));
    let src = v.get("src").and_then(Value::as_i64);
    match kind {
        "poly" => Stroke::Poly {
            pts: pts(&v["pts"]),
            free: v.get("free").is_some_and(b),
            smooth: v.get("smooth").map_or(0, i),
            k: v.get("k").map_or(1.0, f),
            src,
        },
        "curve" => Stroke::Curve {
            pts: pts(&v["pts"]),
            sharp: v
                .get("sharp")
                .and_then(Value::as_array)
                .map(|a| a.iter().map(|x| i(x) as usize).collect())
                .unwrap_or_default(),
            sym: v.get("sym").map(sym_of).unwrap_or(None),
            src,
        },
        "arc" => Stroke::Arc {
            pts: pts(&v["pts"]),
            k: v.get("k").map_or(1.0, f),
            src,
        },
        "ellipse" => {
            let b = floats(&v["box"]);
            Stroke::Ellipse {
                box_: [b[0], b[1], b[2], b[3]],
                src,
            }
        }
        other => panic!("unknown stroke {other}"),
    }
}

fn strokes_of(v: &Value) -> Vec<Stroke> {
    v.as_array()
        .expect("strokes is not an array")
        .iter()
        .map(stroke_of)
        .collect()
}

fn tumour_of(v: &Value) -> Tumour {
    let mut tm = Tumour::default();
    if let Some(x) = v.get("on") {
        tm.on = b(x);
    }
    if let Some(s) = v.get("shape").and_then(Value::as_str) {
        tm.shape = match s {
            "triangle" => TumourShape::Triangle,
            "square" => TumourShape::Square,
            "circle" => TumourShape::Circle,
            "parabola" => TumourShape::Parabola,
            other => panic!("unknown tumour shape {other}"),
        };
    }
    if let Some(s) = v.get("side").and_then(Value::as_str) {
        tm.side = match s {
            "alt" => TumourSide::Alt,
            "left" => TumourSide::Left,
            "right" => TumourSide::Right,
            "random" => TumourSide::Random,
            other => panic!("unknown tumour side {other}"),
        };
    }
    if let Some(s) = v.get("wrap").and_then(Value::as_str) {
        tm.wrap = match s {
            "simple" => TumourWrap::Simple,
            "wrap" => TumourWrap::Wrap,
            other => panic!("unknown tumour wrap {other}"),
        };
    }
    if let Some(x) = v.get("size") {
        tm.size = f(x);
    }
    if let Some(x) = v.get("length") {
        tm.length = f(x);
    }
    if let Some(x) = v.get("dist") {
        tm.dist = f(x);
    }
    if let Some(x) = v.get("start") {
        tm.start = f(x);
    }
    if let Some(x) = v.get("end") {
        tm.end = f(x);
    }
    if let Some(x) = v.get("ease") {
        tm.ease = f(x);
    }
    if let Some(x) = v.get("k") {
        tm.k = f(x);
    }
    if let Some(x) = v.get("seed") {
        tm.seed = i(x);
    }
    if let Some(x) = v.get("fit") {
        tm.fit = b(x);
    }
    if let Some(x) = v.get("mirror") {
        tm.mirror = b(x);
    }
    tm
}

fn shape_of(v: &Value) -> Shape {
    let kind = kind_of(v["kind"].as_str().expect("shape has no kind"));
    let mut sh = Shape {
        kind,
        pts: v.get("pts").map(pts).unwrap_or_default(),
        ..Shape::default()
    };
    if let Some(x) = v.get("vel0") {
        sh.vel0 = f(x);
    }
    if let Some(x) = v.get("vel1") {
        sh.vel1 = f(x);
    }
    if let Some(x) = v.get("end_dot") {
        sh.end_dot = b(x);
    }
    if let Some(env) = v.get("vel_env").filter(|x| !x.is_null()) {
        sh.vel_env = pts(env);
    }
    if let Some(tm) = v.get("tumour").filter(|x| !x.is_null()) {
        sh.tumour = Some(tumour_of(tm));
    }
    match kind {
        Kind::Free => {
            if let Some(x) = v.get("smooth") {
                sh.smooth = i(x);
            }
            if let Some(x) = v.get("k") {
                sh.k = f(x);
            }
        }
        Kind::Arc => {
            if let Some(x) = v.get("k") {
                sh.k = f(x);
            }
        }
        Kind::Curve => {
            if let Some(a) = v.get("sharp").and_then(Value::as_array) {
                sh.sharp = a.iter().map(|x| i(x) as usize).collect();
            }
            if let Some(x) = v.get("sym") {
                sh.sym = sym_of(x);
            }
            if let Some(a) = v.get("gaps").and_then(Value::as_array) {
                sh.gaps = a.iter().map(|x| i(x) as usize).collect();
            }
            // a joined curve's per-piece tumours / sections (joined.py, from the 1.2.0 join port)
            if let Some(a) = v.get("splits").and_then(Value::as_array) {
                sh.splits = a.iter().map(|x| i(x) as usize).collect();
            }
            if let Some(a) = v.get("tumours").and_then(Value::as_array) {
                sh.tumours = a
                    .iter()
                    .map(|t| {
                        if t.is_null() {
                            None
                        } else {
                            Some(tumour_of(t))
                        }
                    })
                    .collect();
            }
        }
        Kind::Custom => {
            if let Some(x) = v.get("name").and_then(Value::as_str) {
                sh.name = x.to_string();
            }
            if let Some(s) = v.get("strokes") {
                sh.strokes = strokes_of(s);
            }
            if let Some(x) = v.get("fill").and_then(Value::as_str) {
                sh.fill = fill_of(x);
            }
            if let Some(x) = v.get("gate") {
                sh.gate = f(x);
            }
            if let Some(x) = v.get("align").and_then(Value::as_str) {
                sh.align = align_of(x);
            }
            if let Some(x) = v.get("ends").and_then(Value::as_str) {
                sh.ends = ends_of(x);
            }
            if let Some(x) = v.get("union") {
                sh.union = b(x);
            }
            if let Some(x) = v.get("apart") {
                sh.apart = b(x);
            }
            if let Some(x) = v.get("notes").and_then(Value::as_str) {
                sh.notes = Some(x.to_string());
            }
            if let Some(x) = v.get("own_vel") {
                sh.own_vel = b(x);
            }
            if let Some(fr) = v.get("from").filter(|x| !x.is_null()) {
                sh.from = Some(shape_from_of(fr));
            }
        }
        Kind::Line | Kind::Poly | Kind::Funnel => {}
    }
    sh
}

fn shape_from_of(fr: &Value) -> ShapeFrom {
    ShapeFrom {
        shapes: fr["shapes"]
            .as_array()
            .expect("from.shapes is not an array")
            .iter()
            .map(shape_of)
            .collect(),
        strokes: strokes_of(&fr["strokes"]),
        pts: pts(&fr["pts"]),
    }
}

fn shapes_of(v: &Value) -> Vec<Shape> {
    v.as_array()
        .expect("shapes is not an array")
        .iter()
        .map(shape_of)
        .collect()
}

fn paths_of(v: &Value) -> Vec<Vec<Vec<Pt>>> {
    v.as_array()
        .expect("paths is not an array")
        .iter()
        .map(|p| {
            p.as_array()
                .expect("path is not an array")
                .iter()
                .map(pts)
                .collect()
        })
        .collect()
}

fn custom_defaults_of(v: &Value) -> spiderweb_core::custom::CustomDefaults {
    spiderweb_core::custom::CustomDefaults {
        fill: fill_of(v["fill"].as_str().expect("cd.fill")),
        gate: f(&v["gate"]),
        align: align_of(v["align"].as_str().expect("cd.align")),
        ends: ends_of(v["ends"].as_str().expect("cd.ends")),
        union: v.get("union").is_some_and(b),
        apart: v.get("apart").is_some_and(b),
    }
}

/// A `losses` sentence -> the key the Rust enum maps to (upstream wording from lang/en.json).
fn loss_key(sentence: &str) -> String {
    match sentence {
        "Tumours become fixed points: they can't be changed with the tumour settings any more." => {
            "tumours".to_string()
        }
        "\"Last note: starts on it\" is dropped (every stroke ends on its last point)." => {
            "end_dot".to_string()
        }
        other => panic!("unknown loss sentence: {other}"),
    }
}

fn loss_of(loss: Cv::Loss) -> &'static str {
    match loss {
        Cv::Loss::Tumours => "tumours",
        Cv::Loss::EndDot => "end_dot",
    }
}

#[test]
fn convert_vectors() {
    let mut checked = 0;
    for (idx, case) in cases("convert").iter().enumerate() {
        let fname = case["fn"].as_str().unwrap();
        let args = case["args"].as_array().unwrap();
        let out = &case["out"];
        let ctx = format!("#{idx} {fname}");
        match fname {
            "line_strokes" => {
                let sh = shape_of(&args[0]);
                let paths: Vec<Vec<Pt>> = args[1]
                    .as_array()
                    .expect("paths is not an array")
                    .iter()
                    .map(pts)
                    .collect();
                let got = Cv::line_strokes(&sh, &paths);
                assert_strokes_close(&got, &strokes_of(out), &ctx);
            }
            "losses" => {
                let shapes = shapes_of(&args[0]);
                let got: Vec<String> = Cv::losses(&shapes)
                    .into_iter()
                    .map(|l| loss_of(l).to_string())
                    .collect();
                let want: Vec<String> = out
                    .as_array()
                    .expect("losses is not an array")
                    .iter()
                    .map(|v| loss_key(v.as_str().expect("loss is not a string")))
                    .collect();
                assert_eq!(got, want, "{ctx}");
            }
            "to_live" => {
                let shapes = shapes_of(&args[0]);
                let paths = paths_of(&args[1]);
                let defaults = shape_of(&args[2]);
                let cd = custom_defaults_of(&args[3]);
                let got = Cv::to_live(&shapes, &paths, &defaults, &cd);
                assert_shape_close(&got, &shape_of(out), &ctx);
            }
            "originals" => {
                let sh = shape_of(&args[0]);
                let got = Cv::originals(&sh);
                match (got, out.as_array()) {
                    (None, None) => {}
                    (Some(back), Some(want)) => {
                        assert_eq!(
                            back.len(),
                            want.len(),
                            "{ctx}: different number of original shapes"
                        );
                        for (k, (g, w)) in back.iter().zip(want.iter()).enumerate() {
                            assert_shape_close(g, &shape_of(w), &format!("{ctx}[{k}]"));
                        }
                    }
                    (got, want) => panic!("{ctx}: originals differ got={got:?} want={want:?}"),
                }
            }
            other => panic!("unknown case {other}"),
        }
        checked += 1;
    }
    assert!(checked >= 25, "too few cases: {checked}");
}
