//! joined.py reference vectors (generated by tools/gen_joined_vectors.py against 1.2.0).

mod common;

use common::*;
use serde_json::Value;
use spiderweb_core::custom::{clean_strokes, stroke_points};
use spiderweb_core::joined as J;
use spiderweb_core::shape::{Align, Fill, Kind, Shape};
use spiderweb_core::tumour::clean_tumour;
use spiderweb_core::{Pt, dist};

fn close(a: f64, b: f64) -> bool {
    let d = (a - b).abs();
    d <= 1e-9 || d <= 1e-9 * a.abs().max(b.abs())
}

fn ints(v: &Value) -> Vec<usize> {
    v.as_array()
        .expect("not an array")
        .iter()
        .map(|x| x.as_u64().unwrap_or_else(|| panic!("not an integer: {x}")) as usize)
        .collect()
}

/// Shape keys are often left out when empty: missing / null counts as no marks.
fn ints_or_empty(v: &Value) -> Vec<usize> {
    if v.is_null() { Vec::new() } else { ints(v) }
}

fn opt_f(v: &Value) -> Option<f64> {
    if v.is_null() { None } else { Some(f(v)) }
}

fn opt_i(v: &Value) -> Option<i64> {
    if v.is_null() { None } else { Some(i(v)) }
}

fn kind_from_str(s: &str) -> Kind {
    match s {
        "line" => Kind::Line,
        "poly" => Kind::Poly,
        "free" => Kind::Free,
        "curve" => Kind::Curve,
        "arc" => Kind::Arc,
        "custom" => Kind::Custom,
        "funnel" => Kind::Funnel,
        _ => panic!("unknown kind {s}"),
    }
}

/// A Shape from a vector input dict (only the fields joined.py looks at).
fn shape_of(v: &Value) -> Shape {
    let mut sh = Shape {
        kind: kind_from_str(v["kind"].as_str().expect("kind")),
        pts: pts(&v["pts"]),
        ..Shape::default()
    };
    if !v["sharp"].is_null() {
        sh.sharp = ints(&v["sharp"]);
    }
    if !v["gaps"].is_null() {
        sh.gaps = ints(&v["gaps"]);
    }
    if !v["splits"].is_null() {
        sh.splits = ints(&v["splits"]);
    }
    if let Some(tm) = v.get("tumour").filter(|t| !t.is_null()) {
        sh.tumour = clean_tumour(tm);
    }
    if let Some(tms) = v.get("tumours").and_then(Value::as_array) {
        sh.tumours = tms.iter().map(clean_tumour).collect();
    }
    if let Some(x) = opt_f(&v["vel0"]) {
        sh.vel0 = x;
    }
    if let Some(x) = opt_f(&v["vel1"]) {
        sh.vel1 = x;
    }
    if !v["vel_env"].is_null() {
        sh.vel_env = pts(&v["vel_env"]);
    }
    if let Some(x) = v.get("end_dot").and_then(Value::as_bool) {
        sh.end_dot = x;
    }
    if let Some(x) = opt_f(&v["k"]) {
        sh.k = x;
    }
    if let Some(x) = opt_i(&v["smooth"]) {
        sh.smooth = x;
    }
    if let Some(strokes) = v.get("strokes").filter(|s| !s.is_null()) {
        sh.strokes = clean_strokes(strokes);
    }
    if let Some(x) = opt_f(&v["gate"]) {
        sh.gate = x.max(1e-6);
    }
    if let Some(x) = v.get("fill").and_then(Value::as_str) {
        sh.fill = match x {
            "fill" => Fill::Fill,
            "spam" => Fill::Spam,
            "outline_spam" => Fill::OutlineSpam,
            _ => Fill::Empty,
        };
    }
    if let Some(x) = v.get("align").and_then(Value::as_str) {
        sh.align = match x {
            "aligned" => Align::Aligned,
            "centred" => Align::Centred,
            _ => Align::Auto,
        };
    }
    if let Some(x) = v.get("name").and_then(Value::as_str) {
        sh.name = x.to_string();
    }
    sh
}

fn tumours_of(v: &Value) -> Vec<Option<spiderweb_core::shape::Tumour>> {
    match v.get("tumours").and_then(Value::as_array) {
        Some(a) => a.iter().map(clean_tumour).collect(),
        None => Vec::new(),
    }
}

/// Compare the shape fields that joined.py sets / keeps.
fn assert_shape_like(got: &Shape, want: &Value, ctx: &str) {
    assert_eq!(
        got.kind.as_str(),
        want["kind"].as_str().unwrap(),
        "{ctx} kind"
    );
    assert_pts_eq(&got.pts, &want["pts"], &format!("{ctx} pts"));
    assert_eq!(got.sharp, ints_or_empty(&want["sharp"]), "{ctx} sharp");
    assert_eq!(got.gaps, ints_or_empty(&want["gaps"]), "{ctx} gaps");
    assert_eq!(got.splits, ints_or_empty(&want["splits"]), "{ctx} splits");
    if let Some(x) = opt_f(&want["vel0"]) {
        assert!(close(got.vel0, x), "{ctx} vel0: {} vs {x}", got.vel0);
    }
    if let Some(x) = opt_f(&want["vel1"]) {
        assert!(close(got.vel1, x), "{ctx} vel1: {} vs {x}", got.vel1);
    }
    if !want["vel_env"].is_null() {
        assert_pts_eq(&got.vel_env, &want["vel_env"], &format!("{ctx} vel_env"));
    }
    if !want["sym"].is_null() {
        assert_eq!(
            got.sym.map(|s| match s {
                spiderweb_core::shape::Sym::Mirror => "mirror",
                spiderweb_core::shape::Sym::Turn => "turn",
            }),
            want["sym"].as_str(),
            "{ctx} sym"
        );
    } else {
        assert!(got.sym.is_none(), "{ctx}: sym should be none");
    }
    let want_tm = want
        .get("tumour")
        .filter(|t| !t.is_null())
        .and_then(clean_tumour);
    assert_eq!(got.tumour, want_tm, "{ctx} tumour");
    assert_eq!(got.tumours, tumours_of(want), "{ctx} tumours");
}

fn assert_tm_eq(got: Option<spiderweb_core::shape::Tumour>, want: &Value, ctx: &str) {
    let want = if want.is_null() {
        None
    } else {
        clean_tumour(want)
    };
    assert_eq!(got, want, "{ctx}");
}

#[test]
fn joined_vectors() {
    let mut checked = 0;
    for (idx, case) in cases("joined").iter().enumerate() {
        let fname = case["fn"].as_str().unwrap();
        let args = case["args"].as_array().unwrap();
        let out = &case["out"];
        let ctx = format!("#{idx} {fname}");
        match fname {
            "to_bezier" => {
                let (got_pts, got_sharp) = J::to_bezier(&shape_of(&args[0]), f(&args[1]));
                assert_pts_eq(&got_pts, &out["pts"], &format!("{ctx} pts"));
                assert_eq!(got_sharp, ints(&out["sharp"]), "{ctx} sharp");
            }
            "reversed_bezier" => {
                let (got_pts, got_sharp) = J::reversed_bezier(&pts(&args[0]), &ints(&args[1]));
                assert_pts_eq(&got_pts, &out[0], &format!("{ctx} pts"));
                assert_eq!(got_sharp, ints(&out[1]), "{ctx} sharp");
            }
            "reversed_tumour" => {
                let tm = clean_tumour(&args[0]).expect("tumour");
                let got = J::reversed_tumour(&tm);
                assert_tm_eq(Some(got), out, &ctx);
            }
            "join_shapes" => {
                let shapes: Vec<Shape> = args[0]
                    .as_array()
                    .unwrap()
                    .iter()
                    .filter(|v| v.is_object())
                    .map(shape_of)
                    .collect();
                let k = f(&args[1]);
                let tol = f(&args[2]);
                let touch = move |p: Pt, q: Pt| dist(p, q) <= tol;
                let got = J::join_shapes(&shapes, k, &touch);
                if out.is_null() {
                    assert!(got.is_none(), "{ctx}: should be None");
                } else {
                    assert_shape_like(&got.expect("joined"), out, &ctx);
                }
            }
            "joined_paths" => {
                let got = J::joined_paths(&shape_of(&args[0]));
                let want = out.as_array().unwrap();
                assert_eq!(got.len(), want.len(), "{ctx}: path count");
                for (k, path) in got.iter().enumerate() {
                    assert_pts_eq(path, &want[k], &format!("{ctx} path {k}"));
                }
            }
            "is_joined" => {
                assert_eq!(J::is_joined(&shape_of(&args[0])), b(out), "{ctx}");
            }
            "all_tumours" => {
                let sh = shape_of(&args[0]);
                let got = J::all_tumours(&sh);
                let want = out.as_array().unwrap();
                assert_eq!(got.len(), want.len(), "{ctx}: count");
                for (k, tm) in got.iter().enumerate() {
                    assert_tm_eq(Some((*tm).clone()), &want[k], &format!("{ctx} #{k}"));
                }
            }
            "shown_tumour" => {
                let sh = shape_of(&args[0]);
                assert_tm_eq(J::shown_tumour(&sh).cloned(), out, &ctx);
            }
            "unify_tumours" => {
                let mut sh = shape_of(&args[0]);
                J::unify_tumours(&mut sh);
                assert_tm_eq(sh.tumour.clone(), &out["tumour"], &format!("{ctx} tumour"));
                assert_tm_eq(
                    None,
                    &Value::Null,
                    &format!("{ctx} tumours must be gone: {:?}", sh.tumours),
                );
                assert!(sh.tumours.is_empty() && sh.splits.is_empty(), "{ctx}");
                let want_tm: Vec<Option<spiderweb_core::shape::Tumour>> =
                    out["tumours"].as_array().map_or(Vec::new(), |_| Vec::new());
                assert_eq!(sh.tumours, want_tm, "{ctx} tumours key must be gone");
            }
            "sections" => {
                let got = J::sections(&shape_of(&args[0]));
                let want = out.as_array().unwrap();
                assert_eq!(got.len(), want.len(), "{ctx}: section count");
                for (k, (a, b2, tm)) in got.iter().enumerate() {
                    assert_eq!(*a as i64, i(&want[k][0]), "{ctx} #{k} first");
                    assert_eq!(*b2 as i64, i(&want[k][1]), "{ctx} #{k} last");
                    assert_tm_eq(tm.clone(), &want[k][2], &format!("{ctx} #{k} tumour"));
                }
            }
            "split_pieces" => {
                let got = J::split_pieces(&shape_of(&args[0]));
                let want = out.as_array().unwrap();
                assert_eq!(got.len(), want.len(), "{ctx}: piece count");
                for (k, sh) in got.iter().enumerate() {
                    assert_shape_like(sh, &want[k], &format!("{ctx} piece {k}"));
                }
            }
            "split_at" => {
                let sh = shape_of(&args[0]);
                let a = args[1].as_u64().unwrap() as usize;
                let got = J::split_at(&sh, a);
                if out.is_null() {
                    assert!(got.is_none(), "{ctx}: should be None");
                } else {
                    let (left, right) = got.expect("halves");
                    assert_shape_like(&left, &out[0], &format!("{ctx} left"));
                    assert_shape_like(&right, &out[1], &format!("{ctx} right"));
                }
            }
            "clean_joined" => {
                let mut out_shape = shape_of(&args[0]);
                let extra = args[1].as_object().expect("extra object");
                J::clean_joined(extra, &mut out_shape);
                assert_pts_eq(&out_shape.pts, &out["pts"], &format!("{ctx} pts"));
                assert_eq!(out_shape.sharp, ints(&out["sharp"]), "{ctx} sharp");
                assert_eq!(out_shape.gaps, ints(&out["gaps"]), "{ctx} gaps");
                assert_eq!(out_shape.splits, ints(&out["splits"]), "{ctx} splits");
                assert_tm_eq(
                    out_shape.tumour.clone(),
                    &out["tumour"],
                    &format!("{ctx} tumour"),
                );
                assert_eq!(out_shape.tumours, tumours_of(out), "{ctx} tumours");
            }
            "piece_velocity" => {
                let mut new = shape_of(&args[0]);
                let old = shape_of(&args[1]);
                let ns = (f(&args[2][0]), f(&args[2][1]));
                let os_ = (f(&args[3][0]), f(&args[3][1]));
                J::piece_velocity(&mut new, &old, ns, os_);
                if !out["vel0"].is_null() {
                    assert!(close(new.vel0, f(&out["vel0"])), "{ctx} vel0");
                    assert!(close(new.vel1, f(&out["vel1"])), "{ctx} vel1");
                }
                if !out["vel_env"].is_null() {
                    assert_pts_eq(&new.vel_env, &out["vel_env"], &format!("{ctx} vel_env"));
                } else {
                    assert!(new.vel_env.is_empty(), "{ctx}: vel_env should be empty");
                }
            }
            "join_velocity" => {
                let olds: Vec<Shape> = args[0].as_array().unwrap().iter().map(shape_of).collect();
                let spans: Vec<(f64, f64)> = args[1]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|s| (f(&s[0]), f(&s[1])))
                    .collect();
                let ns = (f(&args[2][0]), f(&args[2][1]));
                let mut new = Shape::default();
                J::join_velocity(&mut new, &olds, &spans, ns);
                if !out["vel0"].is_null() {
                    assert!(close(new.vel0, f(&out["vel0"])), "{ctx} vel0");
                    assert!(close(new.vel1, f(&out["vel1"])), "{ctx} vel1");
                }
                if !out["vel_env"].is_null() {
                    assert_pts_eq(&new.vel_env, &out["vel_env"], &format!("{ctx} vel_env"));
                } else {
                    assert!(new.vel_env.is_empty(), "{ctx}: vel_env should be empty");
                }
            }
            "custom_groups" => {
                let got = J::custom_groups(&shape_of(&args[0]));
                let want: Vec<Vec<usize>> = out.as_array().unwrap().iter().map(ints).collect();
                assert_eq!(got, want, "{ctx}");
            }
            "split_custom" => {
                let got = J::split_custom(&shape_of(&args[0]));
                let want = out.as_array().unwrap();
                assert_eq!(got.len(), want.len(), "{ctx}: count");
                for (k, sh) in got.iter().enumerate() {
                    assert_pts_eq(&sh.pts, &want[k]["pts"], &format!("{ctx} #{k} frame pts"));
                    let want_strokes = clean_strokes(&want[k]["strokes"]);
                    assert_eq!(
                        sh.strokes.len(),
                        want_strokes.len(),
                        "{ctx} #{k} stroke count"
                    );
                    for (j, (a, b2)) in sh.strokes.iter().zip(want_strokes.iter()).enumerate() {
                        let (ga, gb) = (stroke_points(a), stroke_points(b2));
                        assert_eq!(ga.len(), gb.len(), "{ctx} #{k} stroke {j} point count");
                        for (p, q) in ga.iter().zip(gb.iter()) {
                            assert!(
                                close(p[0], q[0]) && close(p[1], q[1]),
                                "{ctx} #{k} stroke {j}: {p:?} vs {q:?}"
                            );
                        }
                    }
                }
            }
            other => panic!("unknown case {other}"),
        }
        checked += 1;
    }
    assert!(checked >= 70, "too few cases: {checked}");
}
