//! Differential tests for files/midi_out.py (vectors generated by tools/gen_io_vectors.py).
//!
//! The primary assertion: the file Rust writes is byte-for-byte identical to Python's (hex
//! comparison). It also hand-parses the SMF header to confirm it is a valid format 1 (without
//! relying on any MIDI library).

mod common;

use common::*;
use serde_json::Value;
use spiderweb_io::midi::{CHANNELS, PPQ_WARN, midi_bytes, slot_track_channel, track_data, vlq};

/// Hand-parse the SMF header: "MThd", length 6, format 1, division = ppq; immediately followed by "MTrk".
fn assert_smf_format1(bytes: &[u8], ppq: u16, name: &str) {
    assert!(bytes.len() > 14, "{name}: file too short");
    assert_eq!(&bytes[0..4], b"MThd", "{name}: no MThd");
    let hlen = u32::from_be_bytes([bytes[4], bytes[5], bytes[6], bytes[7]]);
    assert_eq!(hlen, 6, "{name}: MThd length");
    let format = u16::from_be_bytes([bytes[8], bytes[9]]);
    assert_eq!(format, 1, "{name}: not format 1");
    let ntrks = u16::from_be_bytes([bytes[10], bytes[11]]);
    assert!(ntrks >= 1, "{name}: no tracks");
    let division = u16::from_be_bytes([bytes[12], bytes[13]]);
    assert_eq!(division, ppq, "{name}: division is not PPQ");
    assert_eq!(&bytes[14..18], b"MTrk", "{name}: first chunk is not MTrk");
}

fn notes6(v: &Value) -> Vec<[i64; 6]> {
    v.as_array()
        .expect("notes is not an array")
        .iter()
        .map(|row| {
            let r = row.as_array().expect("note is not an array");
            let mut n = [0i64; 6];
            for (k, x) in r.iter().enumerate() {
                n[k] = i(x);
            }
            n
        })
        .collect()
}

#[test]
fn midi_byte_vectors() {
    let cases = cases("midi", "cases");
    for case in &cases {
        let name = s(&case["name"]);
        let ppq = case["ppq"].as_u64().expect("ppq") as u16;
        let bpm = f(&case["bpm"]);
        let beats = case["beats"].as_u64().expect("beats") as u8;
        let notes = notes6(&case["notes"]);
        let got = midi_bytes(ppq, bpm, beats, &notes).unwrap_or_else(|e| panic!("{name}: {e}"));
        let want = unhex(s(&case["hex"]));
        assert_eq!(got, want, "{name}: MIDI is not byte-identical");

        assert_smf_format1(&got, ppq, name);
    }
}

#[test]
fn midi_helpers() {
    assert_eq!(vlq(0), vec![0x00]);
    assert_eq!(vlq(0x7F), vec![0x7F]);
    assert_eq!(vlq(0x80), vec![0x81, 0x00]);
    assert_eq!(vlq(0x3FFF), vec![0xFF, 0x7F]);
    assert_eq!(vlq(0x4000), vec![0x81, 0x80, 0x00]);
    assert_eq!(vlq(0x1FFFFF), vec![0xFF, 0xFF, 0x7F]);
    assert_eq!(vlq(0x200000), vec![0x81, 0x80, 0x80, 0x00]);
    // one channel per slot, skipping drum channel 10 (9 zero-based)
    assert_eq!(slot_track_channel(0), (0, CHANNELS[0]));
    assert_eq!(slot_track_channel(9), (9, 10));
    assert_eq!(slot_track_channel(14), (14, 15));
    assert_eq!(slot_track_channel(15), (15, CHANNELS[0]));
    assert_eq!(slot_track_channel(-1), (-1, CHANNELS[14]));
    assert_eq!(PPQ_WARN, 32767);
    // empty track: only the end-of-track marker
    assert_eq!(track_data(&[], 0), vec![0x00, 0xFF, 0x2F, 0x00]);
    // note-off comes first at the same tick
    let notes = [[0i64, 0, 60, 100, 0, 0]];
    assert_eq!(
        track_data(&notes, 0),
        vec![
            0x00, 0x80, 60, 0x00, 0x00, 0x90, 60, 100, 0x00, 0xFF, 0x2F, 0x00
        ]
    );
}
