//! Differential tests for files/project.py (vectors generated by tools/gen_io_vectors.py).
//!
//! The vectors are project text saved by Python `project_json(project_data)` and the expected
//! fields computed with `load_file` semantics. Rust side: parse -> deep-compare field by
//! field; then serialise -> the Python layout still holds the same data.

mod common;

use common::*;
use serde_json::Value;
use spiderweb_io::project::Project;

#[test]
fn project_load_vectors() {
    let cases = cases("project", "cases");
    for case in &cases {
        let name = s(&case["name"]);
        if let Some(err) = case.get("error").and_then(Value::as_str) {
            panic!("failed to generate vector {name}: {err}");
        }
        let saved = s(&case["saved"]);
        let data: Value = serde_json::from_str(saved).expect("saved is not JSON");
        let project = Project::from_json(&data)
            .unwrap_or_else(|e| panic!("{name}: project parse failed: {e}"));
        let got = project.to_json();
        assert_json_eq(
            &got,
            &project_want(&case["expected"]),
            &format!("{name}: load"),
        );

        // Python layout -> valid JSON -> semantically identical to to_json (Python can read it back)
        let text = project.to_project_json();
        let reparsed: Value = serde_json::from_str(&text)
            .unwrap_or_else(|e| panic!("{name}: to_project_json is not JSON: {e}\n{text}"));
        assert_json_eq(&reparsed, &got, &format!("{name}: to_project_json"));

        // atomic write to disk and read back is exactly identical
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("project.json");
        project.write(&path, None).expect("write project");
        let loaded = Project::load(&path).expect("read project");
        assert_eq!(loaded, project, "{name}: write then read back");
    }
}

#[test]
fn keys_round_trip() {
    // 1.2.0's 256-key setting: 256 round-trips; missing / any other value is always 128
    let p = Project::from_json(&serde_json::json!({"keys": 256})).expect("read project");
    assert_eq!(p.keys, 256);
    assert_eq!(p.to_json()["keys"], serde_json::json!(256));
    let text = p.to_project_json();
    let again = Project::from_json(&serde_json::from_str(&text).expect("JSON")).expect("read back");
    assert_eq!(again.keys, 256);
    assert_eq!(
        Project::from_json(&serde_json::json!({}))
            .expect("read project")
            .keys,
        128
    );
    assert_eq!(
        Project::from_json(&serde_json::json!({"keys": "256"}))
            .expect("read project")
            .keys,
        128
    );
}

#[test]
fn read_project_settings() {
    // PPQ / BPM / beats are text fields and may be expressions (window/app.py read_project)
    let mut p = Project {
        ppq: "960*2".to_string(),
        bpm: "60+60".to_string(),
        beats: "3+1".to_string(),
        ..Project::default()
    };
    assert_eq!(p.read_project().expect("evaluate"), (1920, 120.0, 4));
    p.ppq = "0".to_string();
    assert_eq!(
        p.read_project().expect_err("PPQ out of range").to_string(),
        "PPQ must be a whole number from 1 to 65535"
    );
    p.ppq = "960".to_string();
    p.bpm = "1".to_string();
    assert_eq!(
        p.read_project().expect_err("BPM too small").to_string(),
        "BPM must be a number, at least 4"
    );
    p.bpm = "120".to_string();
    p.beats = "33".to_string();
    assert_eq!(
        p.read_project()
            .expect_err("beats out of range")
            .to_string(),
        "Beats per bar must be a whole number from 1 to 32"
    );
}

#[test]
fn project_error_vectors() {
    // Bad shapes / defaults make the whole project fail to open (Python load_file returns False)
    for bad in [
        serde_json::json!({"shapes": null}),
        serde_json::json!({"shapes": 5}),
        serde_json::json!({"defaults": [1]}),
        serde_json::json!({"defaults": {"vel0": "abc"}}),
        serde_json::json!({"shapes": [{"kind": "line", "pts": [[0]]}]}),
    ] {
        assert!(
            Project::from_json(&bad).is_err(),
            "bad project should error: {bad}"
        );
    }
    // Unsupported shape kinds are just skipped, not a read failure
    let p = Project::from_json(&serde_json::json!({
        "shapes": [{"kind": "blob", "pts": [[0, 0], [1, 1]]}, {"kind": "line", "pts": [[0, 0], [1, 1]]}]
    }))
    .expect("should read");
    assert_eq!(p.shapes.len(), 1);
}
