[package]
name = "spiderweb-io"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
spiderweb-core = { path = "../spiderweb-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
midly = { workspace = true }
tempfile = "3"
