//! Shared part of the differential tests: read the vectors generated by tools/gen_*_vectors.py.

#![allow(dead_code)]

use serde_json::Value;
use spiderweb_core::Note;

pub fn cases(module: &str) -> Vec<Value> {
    let path = format!("{}/tests/vectors/{module}.json", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("missing vector file {path} (run tools/gen_{module}_vectors.py first): {e}")
    });
    let data: Value = serde_json::from_str(&text).expect("failed to parse vector JSON");
    data["cases"]
        .as_array()
        .expect("cases is not an array")
        .clone()
}

pub fn f(v: &Value) -> f64 {
    v.as_f64().unwrap_or_else(|| panic!("not a number: {v}"))
}

pub fn i(v: &Value) -> i64 {
    v.as_i64().unwrap_or_else(|| panic!("not an integer: {v}"))
}

pub fn b(v: &Value) -> bool {
    v.as_bool().unwrap_or_else(|| panic!("not a bool: {v}"))
}

pub fn pts(v: &Value) -> Vec<[f64; 2]> {
    v.as_array()
        .expect("not an array")
        .iter()
        .map(|p| {
            let a = p.as_array().expect("point is not an array");
            [f(&a[0]), f(&a[1])]
        })
        .collect()
}

pub fn rows3(v: &Value) -> Vec<[i64; 3]> {
    v.as_array()
        .expect("not an array")
        .iter()
        .map(|p| {
            let a = p.as_array().expect("row is not an array");
            [i(&a[0]), i(&a[1]), i(&a[2])]
        })
        .collect()
}

pub fn rows_i64(v: &Value) -> Vec<Vec<i64>> {
    v.as_array()
        .expect("not an array")
        .iter()
        .map(|r| {
            r.as_array()
                .expect("row is not an array")
                .iter()
                .map(i)
                .collect()
        })
        .collect()
}

pub fn floats(v: &Value) -> Vec<f64> {
    v.as_array().expect("not an array").iter().map(f).collect()
}

/// A compact [`Note`] as the `(start, end, key, velocity)` i64 row the vectors use.
pub fn note_row4(n: &Note) -> [i64; 4] {
    [n.start as i64, n.end as i64, n.key as i64, n.vel as i64]
}

/// The compact notes as the `(start, end, key, velocity, slot, owner)` i64 rows the vectors use.
pub fn note_rows6(notes: &[Note]) -> Vec<[i64; 6]> {
    notes.iter().map(|n| n.row6()).collect()
}

fn close(a: f64, b: f64) -> bool {
    let d = (a - b).abs();
    d <= 1e-9 || d <= 1e-9 * a.abs().max(b.abs())
}

pub fn assert_pts_eq(got: &[[f64; 2]], want: &Value, ctx: &str) {
    let w = pts(want);
    assert_eq!(
        got.len(),
        w.len(),
        "{ctx}: different number of points got={got:?} want={w:?}"
    );
    for (k, (g, x)) in got.iter().zip(w.iter()).enumerate() {
        assert!(
            close(g[0], x[0]) && close(g[1], x[1]),
            "{ctx}: point {k} differs got={g:?} want={x:?}"
        );
    }
}

pub fn assert_rows3_eq(got: &[[i64; 3]], want: &Value, ctx: &str) {
    let w = rows3(want);
    assert_eq!(got, w.as_slice(), "{ctx}");
}
