//! Shared pieces of the spiderweb-io differential tests: vector loading and deep JSON comparison with numeric tolerance.

#![allow(dead_code)]

use serde_json::{Map, Value};

pub fn cases(module: &str, key: &str) -> Vec<Value> {
    let path = format!("{}/tests/vectors/{module}.json", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("missing vector file {path} (run tools/gen_io_vectors.py first): {e}")
    });
    let data: Value = serde_json::from_str(&text).expect("failed to parse vector JSON");
    data[key].as_array().expect("cases is not an array").clone()
}

pub fn f(v: &Value) -> f64 {
    v.as_f64().unwrap_or_else(|| panic!("not a number: {v}"))
}

pub fn i(v: &Value) -> i64 {
    v.as_i64().unwrap_or_else(|| panic!("not an integer: {v}"))
}

pub fn s(v: &Value) -> &str {
    v.as_str().unwrap_or_else(|| panic!("not a string: {v}"))
}

fn close(a: f64, b: f64) -> bool {
    if a == b {
        return true;
    }
    if a.is_nan() && b.is_nan() {
        return true;
    }
    let d = (a - b).abs();
    d <= 1e-9 || d <= 1e-9 * a.abs().max(b.abs())
}

/// Deep comparison with numeric tolerance and identical structure (key order does not matter).
pub fn json_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(_), Value::Number(_)) => a
            .as_f64()
            .is_some_and(|x| b.as_f64().is_some_and(|y| close(x, y))),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| json_eq(p, q))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len()
                && x.iter()
                    .all(|(k, v)| y.get(k).is_some_and(|w| json_eq(v, w)))
        }
        _ => a == b,
    }
}

pub fn assert_json_eq(got: &Value, want: &Value, ctx: &str) {
    if !json_eq(got, want) {
        panic!(
            "{ctx}:\n  got  {}\n  want {}",
            serde_json::to_string(got).unwrap_or_default(),
            serde_json::to_string(want).unwrap_or_default()
        );
    }
}

/// The 1.2.0 tumour keys a 1.1.0-generated vector doesn't spell out (they default to 0).
fn tumour_want(v: &Value) -> Value {
    let Some(d) = v.as_object() else {
        return v.clone();
    };
    let mut out: Map<String, Value> = d.clone();
    out.entry("rot").or_insert(Value::from(0.0));
    out.entry("slant").or_insert(Value::from(0.0));
    Value::Object(out)
}

/// Shape comparison: Python `clean_shape` writes smooth/k for a free shape only when the file
/// has "smooth", while Rust `Shape` always carries them; fill in the defaults before comparing.
/// A tumour's rot / slant are new in 1.2.0 and absent from vectors generated by the 1.1.0
/// reference (default 0), so fill those in too.
pub fn shape_want(v: &Value) -> Value {
    let Some(d) = v.as_object() else {
        return v.clone();
    };
    let mut out: Map<String, Value> = d.clone();
    if d.get("kind").and_then(Value::as_str) == Some("free") {
        out.entry("smooth").or_insert(Value::from(0));
        out.entry("k").or_insert(Value::from(1.0));
    }
    if let Some(tm) = out.get("tumour").cloned() {
        out.insert("tumour".into(), tumour_want(&tm));
    }
    if let Some(Value::Array(list)) = out.get("tumours").cloned() {
        out.insert(
            "tumours".into(),
            Value::Array(
                list.iter()
                    .map(|t| {
                        if t.is_null() {
                            t.clone()
                        } else {
                            tumour_want(t)
                        }
                    })
                    .collect(),
            ),
        );
    }
    Value::Object(out)
}

/// Project comparison: every shape inside also goes through [`shape_want`].
pub fn project_want(v: &Value) -> Value {
    let mut out = v.clone();
    if let Some(shapes) = out.get_mut("shapes").and_then(Value::as_array_mut) {
        for sh in shapes.iter_mut() {
            *sh = shape_want(sh);
        }
    }
    out
}

pub fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("not hexadecimal"))
        .collect()
}
