//! Differential tests for domino_clip.py (vectors generated by tools/gen_domino_vectors.py).

use flate2::read::ZlibDecoder;
use serde_json::Value;
use spiderweb_domino::{DominoStart, Error, MAGIC, clip_data, read_notes, read_notes_max_key};
use std::io::Read;

fn vectors() -> Value {
    let path = format!("{}/tests/vectors/domino.json", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("missing vector file {path} (run tools/gen_domino_vectors.py first): {e}")
    });
    serde_json::from_str(&text).expect("failed to parse vector JSON")
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("not hexadecimal"))
        .collect()
}

fn i(v: &Value) -> i64 {
    v.as_i64().unwrap_or_else(|| panic!("not an integer: {v}"))
}

fn notes6(v: &Value) -> Vec<[i64; 6]> {
    v.as_array()
        .expect("notes is not an array")
        .iter()
        .map(|row| {
            let r = row.as_array().expect("notes row is not an array");
            let mut n = [0i64; 6];
            for (k, x) in r.iter().enumerate() {
                n[k] = i(x);
            }
            n
        })
        .collect()
}

fn rows5(v: &Value) -> Vec<[i64; 5]> {
    v.as_array()
        .expect("rows is not an array")
        .iter()
        .map(|row| {
            let r = row.as_array().expect("rows row is not an array");
            [i(&r[0]), i(&r[1]), i(&r[2]), i(&r[3]), i(&r[4])]
        })
        .collect()
}

fn size_field(raw: &[u8]) -> usize {
    u32::from_le_bytes(
        raw[MAGIC.len()..MAGIC.len() + 4]
            .try_into()
            .expect("size field"),
    ) as usize
}

fn decompress(raw: &[u8]) -> Vec<u8> {
    let mut dec = ZlibDecoder::new(&raw[MAGIC.len() + 4..]);
    let mut out = Vec::new();
    dec.read_to_end(&mut out).expect("decompression failed");
    out
}

fn case_name(case: &Value) -> &str {
    case["name"].as_str().expect("case has no name")
}

fn start_of(case: &Value) -> DominoStart {
    match case["start"].as_str().expect("case has no start") {
        "note" => DominoStart::Note,
        "bar" => DominoStart::Bar,
        other => panic!("unknown start {other}"),
    }
}

/// clip_data: Rust's decompressed payload must be byte-for-byte identical to Python's, and Rust must read it back itself.
#[test]
fn clip_vectors() {
    let data = vectors();
    let cases = data["clip"].as_array().expect("clip is not an array");
    let (mut saw_note, mut saw_bar) = (false, false);
    for case in cases {
        let name = case_name(case);
        let notes = notes6(&case["notes"]);
        let ppq = case["ppq"].as_u64().expect("ppq") as u16;
        let bar = i(&case["bar"]);
        let start = start_of(case);
        match start {
            DominoStart::Note => saw_note = true,
            DominoStart::Bar => saw_bar = true,
        }
        let py_raw = unhex(case["raw"].as_str().expect("raw"));
        let py_payload = unhex(case["payload"].as_str().expect("payload"));

        let got = clip_data(&notes, ppq, bar, start).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(got.starts_with(MAGIC), "{name}: wrong magic");
        assert_eq!(
            size_field(&got),
            py_payload.len(),
            "{name}: wrong size field"
        );
        assert_eq!(
            decompress(&got),
            py_payload,
            "{name}: decompressed payload differs from Python"
        );
        assert_eq!(
            decompress(&py_raw),
            py_payload,
            "{name}: Python vector self-check failed"
        );

        let rust = read_notes(&got).unwrap_or_else(|e| panic!("{name}: read-back failed {e}"));
        let py =
            read_notes(&py_raw).unwrap_or_else(|e| panic!("{name}: reading Python raw failed {e}"));
        assert_eq!(
            rust, py,
            "{name}: Rust raw read-back differs from Python raw"
        );
    }
    assert!(cases.len() >= 9, "too few clips cases: {}", cases.len());
    assert!(
        saw_note && saw_bar,
        "the clip vectors must cover both the note and bar starts"
    );
    assert_eq!(
        DominoStart::default(),
        DominoStart::Bar,
        "clip_data's default start"
    );
}

/// clip_data's error semantics: empty, bar 0, length exceeding u32.
#[test]
fn clip_error_vectors() {
    let data = vectors();
    let cases = data["clip_errors"]
        .as_array()
        .expect("clip_errors is not an array");
    for case in cases {
        let name = case_name(case);
        let notes = notes6(&case["notes"]);
        let ppq = case["ppq"].as_u64().expect("ppq") as u16;
        let bar = i(&case["bar"]);
        let want = match case["error"].as_str().expect("error") {
            "empty" => Error::Empty,
            "bad_bar" => Error::BadBar,
            "too_large" => Error::TooLarge,
            other => panic!("unknown error kind {other}"),
        };
        assert_eq!(
            clip_data(&notes, ppq, bar, start_of(case)),
            Err(want),
            "{name}"
        );
    }
    assert!(
        cases.len() >= 3,
        "too few clip_errors cases: {}",
        cases.len()
    );
}

/// read_notes: read Python-generated raw directly (including real clipboard layouts and bad data).
#[test]
fn read_vectors() {
    let data = vectors();
    let cases = data["read"].as_array().expect("read is not an array");
    for case in cases {
        let name = case_name(case);
        let raw = unhex(case["raw"].as_str().expect("raw"));
        if let Some(kind) = case["error"].as_str() {
            let want = match kind {
                "not_domino" => Error::NotDomino,
                "damaged" => Error::Damaged,
                other => panic!("unknown error kind {other}"),
            };
            assert_eq!(read_notes(&raw), Err(want), "{name}");
        } else {
            let (rows, ppq) = read_notes(&raw).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(rows, rows5(&case["rows"]), "{name}");
            let want_ppq = case["ppq"].as_u64().map(|p| p as u16);
            assert_eq!(ppq, want_ppq, "{name}");
        }
    }
    assert!(cases.len() >= 30, "too few read cases: {}", cases.len());
}

/// The clipboard stub on non-Windows platforms.
#[cfg(not(windows))]
#[test]
fn clipboard_stub() {
    assert!(!spiderweb_domino::put_on_clipboard(b"x"));
    assert_eq!(
        spiderweb_domino::get_from_clipboard(),
        spiderweb_domino::ClipboardGet::NoData
    );
}

#[test]
fn high_keys_round_trip_with_max_key() {
    // A note item's key is a u8: key 200 fits; default reading drops >127 as the original does,
    // while the 256k setting (max_key = 255) reads it back unchanged.
    let notes = vec![[0i64, 100, 200, 80, 0, 0]];
    let raw = clip_data(&notes, 960, 3840, DominoStart::Bar).expect("encode");
    let (rows, _) = read_notes(&raw).expect("read");
    assert!(
        rows.iter().all(|r| r[2] != 200),
        "keys >127 should be dropped by default"
    );
    let (rows, _) = read_notes_max_key(&raw, 255).expect("read");
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0][2], 200);
}
