"""Embedded help clips: copies the upstream clips/ folder and generates crates/spiderweb-app/src/help_clips.rs.

The Help window shows clips/<name>.gif (and clips/<name>.png instead of a GIF: a still picture) next to the
program; this script bundles them into the binary with include_bytes! and writes the name -> bytes lookup
(help_clips::clip_bytes). A name that has both a .gif and a .png uses the GIF, like the upstream add_clip.

Regenerate after copying in a new upstream version:

    python3 tools/gen_help_clips.py --from /path/to/upstream/clips
    python3 tools/gen_help_clips.py   # (re)generate from the committed assets only
"""

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "crates", "spiderweb-app", "assets", "clips")
OUT = os.path.join(ROOT, "crates", "spiderweb-app", "src", "help_clips.rs")


def files():
    """name -> file name, GIF wins over PNG when both are there."""
    chosen = {}
    for f in sorted(os.listdir(ASSETS)):
        stem, ext = os.path.splitext(f)
        if ext not in (".gif", ".png"):
            continue
        if stem not in chosen or ext == ".gif":
            chosen[stem] = f
    return {stem: chosen[stem] for stem in sorted(chosen)}


def main():
    args = sys.argv[1:]
    if args:
        if len(args) != 2 or args[0] != "--from":
            sys.exit(__doc__)
        src = args[1]
        if not os.path.isdir(src):
            sys.exit(f"not a directory: {src}")
        upstream = {f for f in os.listdir(src) if os.path.splitext(f)[1] in (".gif", ".png")}
        copied = removed = 0
        for f in sorted(upstream):
            shutil.copyfile(os.path.join(src, f), os.path.join(ASSETS, f))
            copied += 1
        for f in sorted(os.listdir(ASSETS)):  # gone upstream: dropped from the assets, too
            if os.path.splitext(f)[1] in (".gif", ".png") and f not in upstream:
                os.remove(os.path.join(ASSETS, f))
                removed += 1
        print(f"copied {copied} clips from {src}" + (f", removed {removed} stale" if removed else ""))

    clips = files()
    lines = [
        "//! Embedded help clips (clips/*.gif and *.png next to the program upstream): generated by",
        "//! tools/gen_help_clips.py from crates/spiderweb-app/assets/clips/; do not edit by hand.",
        "//! Regenerate with: python3 tools/gen_help_clips.py",
        "",
        "/// Every embedded clip's name, sorted (GIF preferred when a name has both kinds);",
        "/// the tests walk the whole table with it.",
        "#[cfg(test)]",
        "pub const NAMES: &[&str] = &[",
    ]
    lines += [f'    "{name}",' for name in clips]
    lines += [
        "];",
        "",
        "/// The bytes of an embedded clip by name (no extension), or None when there is no such clip.",
        "/// The help window sniffs the format (GIF / PNG); a missing clip is silently skipped.",
        "pub fn clip_bytes(name: &str) -> Option<&'static [u8]> {",
        "    Some(match name {",
    ]
    lines += [f'        "{name}" => include_bytes!("../assets/clips/{f}"),' for name, f in clips.items()]
    lines += [
        "        _ => return None,",
        "    })",
        "}",
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    # The output is laid out by rustfmt directly, so cargo fmt --check stays clean (skipped without rustfmt)
    try:
        subprocess.run(["rustfmt", "--edition", "2024", OUT], check=True)
    except (OSError, subprocess.CalledProcessError) as e:
        print(f"rustfmt skipped ({e}): run cargo fmt -p spiderweb-app before committing")
    print(f"{len(clips)} clips -> {OUT}")


if __name__ == "__main__":
    main()
