"""Mechanical conversion of help_texts.py: original scripts/window/help_texts.py -> crates/spiderweb-app/src/help_texts.rs.

The original module is imported directly; TOPICS / SECTIONS / NEXT / SEE / TOOL_TOPICS become
Rust constants as they are (strings escaped as Rust literals, non-ASCII kept as UTF-8). To change
the wording, edit the original and run this script again:

    python3 tools/gen_help_texts.py

The original script dir defaults to /Users/jieneng/Documents/GitHub/Spiderweb-main/scripts and
can be overridden with the SPIDERWEB_SCRIPTS environment variable (same convention as
tools/gen_*_vectors.py).
"""

import os
import subprocess
import sys

# when run in the worktree the original script dir cannot be derived; use the same fallback path as gen_*_vectors.py
_SCRIPTS = os.environ.get("SPIDERWEB_SCRIPTS",
                          "/Users/jieneng/Documents/GitHub/Spiderweb-main/scripts")
if os.path.isdir(_SCRIPTS) and _SCRIPTS not in sys.path:
    sys.path.insert(0, _SCRIPTS)

from window.help_texts import NEXT, SECTIONS, SEE, TOOL_TOPICS, TOPICS  # noqa: E402

_OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "crates", "spiderweb-app", "src", "help_texts.rs")


def lit(s):
    """Python string -> Rust string literal (including the quotes)."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def topic(t):
    return ("    Topic {\n"
            f"        id: {lit(t['id'])},\n"
            f"        section: {lit(t['section'])},\n"
            f"        title: {lit(t['title'])},\n"
            f"        tip: {lit(t['tip'])},\n"
            f"        text: {lit(t['text'])},\n"
            f"        words: {lit(t.get('words', ''))},\n"
            "    },")


def main():
    sections = {t["section"] for t in TOPICS}
    missing = sections - set(SECTIONS)
    if missing:
        sys.exit(f"section not in SECTIONS: {sorted(missing)}")
    for t in TOPICS:
        for key in ("id", "section", "title", "tip", "text"):
            if key not in t:
                sys.exit(f"topic {t.get('id', '?')} is missing {key}")
    ids = [t["id"] for t in TOPICS]
    if len(ids) != len(set(ids)):
        sys.exit("duplicate topic id")
    for src, dst in list(NEXT.items()) + [(k, v) for k, vs in SEE.items() for v in vs]:
        for i in (src, dst):
            if i not in ids:
                sys.exit(f"NEXT / SEE reference an unknown topic {i}")

    lines = [
        "//! Help texts: generated by tools/gen_help_texts.py from upstream scripts/window/help_texts.py; do not edit by hand.",
        "//! Regenerate with: python3 tools/gen_help_texts.py",
        "",
        "/// A help topic (an element of upstream TOPICS): tip is the first-use popup / tool button tooltip,",
        "/// text is the full description (help window and side panel; upstream [clip:...] markers are removed).",
        "pub struct Topic {",
        "    pub id: &'static str,",
        "    pub section: &'static str,",
        "    pub title: &'static str,",
        "    pub tip: &'static str,",
        "    pub text: &'static str,",
        "    pub words: &'static str,",
        "}",
        "",
        "/// Section order in the help window.",
        "pub const SECTIONS: &[&str] = &[",
    ]
    lines += [f"    {lit(s)}," for s in SECTIONS]
    lines += [
        "];",
        "",
        "/// All help topics.",
        "pub const TOPICS: &[Topic] = &[",
    ]
    lines += [topic(t) for t in TOPICS]
    lines += [
        "];",
        "",
        "/// The next topic shown after a tip is dismissed (upstream NEXT).",
        "pub const NEXT: &[(&str, &str)] = &[",
    ]
    lines += [f"    ({lit(k)}, {lit(v)})," for k, v in NEXT.items()]
    lines += [
        "];",
        "",
        '/// "See also": topic -> related topics (upstream SEE).',
        "pub const SEE: &[(&str, &[&str])] = &[",
    ]
    for k, vs in SEE.items():
        inner = ", ".join(lit(v) for v in vs)
        lines.append(f"    ({lit(k)}, &[{inner}]),")
    lines += [
        "];",
        "",
        "/// Tip topic for each tool (upstream TOOL_TOPICS; Square / Circle / Triangle share box).",
        "pub const TOOL_TOPICS: &[(&str, &str)] = &[",
    ]
    lines += [f"    ({lit(k)}, {lit(v)})," for k, v in TOOL_TOPICS.items()]
    lines += [
        "];",
        "",
        "/// Finds a topic by id.",
        "pub fn by_id(id: &str) -> Option<&'static Topic> {",
        "    TOPICS.iter().find(|t| t.id == id)",
        "}",
        "",
        "/// Related topics for a topic (empty if absent from SEE).",
        "pub fn see(id: &str) -> &'static [&'static str] {",
        "    SEE.iter().find(|(k, _)| *k == id).map(|(_, v)| *v).unwrap_or(&[])",
        "}",
        "",
        "/// The next topic shown after a tip is dismissed.",
        "pub fn next(id: &str) -> Option<&'static str> {",
        "    NEXT.iter().find(|(k, _)| *k == id).map(|(_, v)| *v)",
        "}",
        "",
        "/// Tool key (upstream tool name) -> tip topic id.",
        "pub fn tool_topic(tool: &str) -> &'static str {",
        "    TOOL_TOPICS",
        "        .iter()",
        "        .find(|(k, _)| *k == tool)",
        "        .map(|(_, v)| *v)",
        '        .unwrap_or("select")',
        "}",
        "",
    ]
    with open(_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    # The output is laid out by rustfmt directly, so cargo fmt --check stays clean (skipped without rustfmt)
    try:
        subprocess.run(["rustfmt", "--edition", "2024", _OUT], check=True)
    except (OSError, subprocess.CalledProcessError) as e:
        print(f"rustfmt skipped ({e}): run cargo fmt -p spiderweb-app before committing")
    print(f"{len(TOPICS)} topics -> {_OUT}")


if __name__ == "__main__":
    main()
