[package]
name = "spiderweb-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
spiderweb-core = { path = "../spiderweb-core" }
spiderweb-domino = { path = "../spiderweb-domino" }
spiderweb-io = { path = "../spiderweb-io" }
eframe = { workspace = true }
egui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
midir = { workspace = true }
rfd = { workspace = true }
bytemuck = { workspace = true }
rust-i18n = { workspace = true }
image = { workspace = true }

[features]
default = []
